from django.core.management.base import BaseCommand
from jobs.models import Job
from datetime import date, timedelta

class Command(BaseCommand):
    help = 'Seed sample jobs'

    def handle(self, *args, **kwargs):
        Job.objects.all().delete()
        jobs = [
            {"title": "Senior Python Developer", "company": "TechCorp India", "company_logo": "https://ui-avatars.com/api/?name=TechCorp&background=6366f1&color=fff", "location": "Hyderabad, Telangana", "job_type": "full-time", "category": "engineering", "description": "Build scalable backend services using Django and FastAPI. Mentor junior developers and design database schemas.", "requirements": "5+ years Python, Django, DRF, PostgreSQL, Docker", "salary_min": 1200000, "salary_max": 2000000, "salary_currency": "INR", "experience_years": 5, "skills": ["Python", "Django", "DRF", "PostgreSQL", "Docker"], "is_featured": True, "deadline": date.today() + timedelta(days=20)},
            {"title": "React Frontend Engineer", "company": "Startup Labs", "company_logo": "https://ui-avatars.com/api/?name=Startup+Labs&background=10b981&color=fff", "location": "Bangalore, Karnataka", "job_type": "full-time", "category": "engineering", "description": "Build performant UIs using React and TypeScript. Work with designers and backend engineers.", "requirements": "3+ years React, TypeScript, Redux, REST APIs", "salary_min": 800000, "salary_max": 1400000, "salary_currency": "INR", "experience_years": 3, "skills": ["React", "TypeScript", "Redux", "Tailwind CSS"], "is_featured": True, "deadline": date.today() + timedelta(days=15)},
            {"title": "Data Scientist", "company": "Analytics Pro", "company_logo": "https://ui-avatars.com/api/?name=Analytics+Pro&background=f59e0b&color=fff", "location": "Mumbai, Maharashtra", "job_type": "full-time", "category": "data", "description": "Analyze large datasets and build ML models to drive business decisions.", "requirements": "Python, Pandas, Scikit-learn, SQL, 3+ years", "salary_min": 1000000, "salary_max": 1800000, "salary_currency": "INR", "experience_years": 3, "skills": ["Python", "Machine Learning", "SQL", "Pandas"], "is_featured": False, "deadline": date.today() + timedelta(days=25)},
            {"title": "DevOps Engineer", "company": "CloudBase Systems", "company_logo": "https://ui-avatars.com/api/?name=CloudBase&background=3b82f6&color=fff", "location": "Pune, Maharashtra", "job_type": "full-time", "category": "engineering", "description": "Manage AWS infrastructure and CI/CD pipelines for our microservices.", "requirements": "AWS, Docker, Kubernetes, Terraform, 4+ years", "salary_min": 1100000, "salary_max": 1900000, "salary_currency": "INR", "experience_years": 4, "skills": ["AWS", "Docker", "Kubernetes", "Terraform"], "is_featured": False, "deadline": date.today() + timedelta(days=18)},
            {"title": "UI/UX Designer", "company": "DesignStudio", "company_logo": "https://ui-avatars.com/api/?name=DesignStudio&background=ec4899&color=fff", "location": "Remote", "job_type": "remote", "category": "design", "description": "Design intuitive user experiences for web and mobile apps.", "requirements": "Figma, Adobe XD, user research, 2+ years", "salary_min": 600000, "salary_max": 1100000, "salary_currency": "INR", "experience_years": 2, "skills": ["Figma", "Adobe XD", "Prototyping", "User Research"], "is_featured": True, "deadline": date.today() + timedelta(days=30)},
            {"title": "Python Django Developer (Fresher)", "company": "WebSolutions India", "company_logo": "https://ui-avatars.com/api/?name=WebSolutions&background=f97316&color=fff", "location": "Hyderabad, Telangana", "job_type": "full-time", "category": "engineering", "description": "Great opportunity for freshers. Build REST APIs and grow in a mentorship-driven environment.", "requirements": "Django, DRF, Python, MySQL, Git, 0-1 years", "salary_min": 300000, "salary_max": 500000, "salary_currency": "INR", "experience_years": 0, "skills": ["Python", "Django", "DRF", "MySQL", "Git"], "is_featured": True, "deadline": date.today() + timedelta(days=14)},
            {"title": "Product Manager", "company": "GrowthCo", "company_logo": "https://ui-avatars.com/api/?name=GrowthCo&background=8b5cf6&color=fff", "location": "Hyderabad, Telangana", "job_type": "full-time", "category": "product", "description": "Drive product strategy and own the roadmap end to end.", "requirements": "5+ years PM, Agile, data-driven mindset", "salary_min": 1500000, "salary_max": 2500000, "salary_currency": "INR", "experience_years": 5, "skills": ["Product Strategy", "Agile", "Jira", "Analytics"], "is_featured": False, "deadline": date.today() + timedelta(days=22)},
            {"title": "Intern - Machine Learning", "company": "AI Ventures", "company_logo": "https://ui-avatars.com/api/?name=AI+Ventures&background=7c3aed&color=fff", "location": "Hyderabad, Telangana", "job_type": "internship", "category": "data", "description": "6-month paid internship on NLP and computer vision projects.", "requirements": "Python, TensorFlow or PyTorch, final year or fresher", "salary_min": 15000, "salary_max": 25000, "salary_currency": "INR", "experience_years": 0, "skills": ["Python", "Machine Learning", "TensorFlow", "NLP"], "is_featured": False, "deadline": date.today() + timedelta(days=8)},
        ]
        for job_data in jobs:
            Job.objects.create(**job_data)
        self.stdout.write(self.style.SUCCESS(f'Seeded {len(jobs)} jobs successfully'))