# Generated by Django 6.0.6 on 2026-06-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('company_logo', models.URLField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote')], default='full-time', max_length=20)),
                ('category', models.CharField(choices=[('engineering', 'Engineering'), ('design', 'Design'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('operations', 'Operations'), ('data', 'Data & Analytics'), ('product', 'Product'), ('other', 'Other')], default='engineering', max_length=50)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(default='INR', max_length=10)),
                ('experience_years', models.IntegerField(default=0)),
                ('skills', models.JSONField(default=list)),
                ('apply_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-is_featured', '-posted_at'],
            },
        ),
    ]
